# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(choices=[('temp', 'temperature'), ('hum', 'Humidity')], max_length=300)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='measure',
            unique_together=set([('name', 'date')]),
        ),
    ]
